### PR TITLE
Shortcuts trackbar

### PR DESCRIPTION
**Pull request by pthom**
Hi,

I do like your library :-)
Actually, I was working on a similar project, but with a less practical API : I do like the "immediate API" paradigm.

So, this is a second pull request (that is based on the first). 
It adds two things :

- nice keyboard shortcuts for the button (if the label is "&Quit" for example, then "Q" will be underlined and set as a shortcut)
- a versatile trackbar for float entry

Cheers

### CODE REVIEW

**Comment by pthom** [comment]
Also see commit https://github.com/pthom/cvui/commit/0a6021c26907c29ac53ce8a31903e20eca7f4266
(which is not on this request)

**Comment by pthom** [comment]
I am sorry for I did not propose this pull request in a very appropriate manner, I should have discussed it with you before. 
Tell me your opinion frankly.
Cheers

**Comment by Dovyski** [comment]
Don't worry that much, I haven't setup any CONTRIBUTION file to guide any help, so that's my fault as well. Regarding your new component, I haven't seen it working yet (I will check it within the next few days).

Inspecting the code I noticed you used a params structure/class. I thought about using that for other components as well in the past, but it breaks the idea of immediate GUI (you need more than a single command to render that component).

We will have to work that out. Maybe we could reduce the number of customization parameter and use default values for that component? I know it will cause the component function to have several parameters, but that's the cost of an immediate GUI approach.

**Comment by pthom** [comment]
Thanks for your answer :-)

>it breaks the idea of immediate GUI (you need more than a single command to render that component).

A quick idea : instead of reducing the customization settings, add some well thought named constructors for the params.
Something like 

`
struct TrackbarParams
{
	double MinimumValue, MaximumValue;
	double SmallStep, LargeStep;
	bool ForceValuesAsMultiplesOfSmallStep;
	bool DrawValuesAtLargeSteps;
	std::string Printf_Format;
	std::string Printf_Format_Steps;

  TrackbarParams Trackbar_WithoutLegend(double min, double max, double nbDecimals = 1);
  TrackbarParams Trackbar_LegendMinMax(double min, double max, double nbDecimals = 1);
  //etc..
};
`
What do you think ?

**Comment by pthom** [comment]
I dit an experiment with named constructors, here  (https://github.com/Dovyski/cvui/pull/6/commits/5661cea94d6db98a4835f9192c8e335bad5a274a)

The visual of the example is 
[trackbar.png](https://postimg.org/image/bm7drhm2p/)

**Comment by pthom** [comment]
I made another modification about your concern about the immediate api.

Now, you have 2 specialized functions, dependog on whether you want to edit integral for floating point values.

````
template <typename T> // T can be any integral type (int, long, char, unsigned int, etc)
bool trackbar_int(T *theValue, T theMin, T theMax, int theNumberOfLargeSteps = 1);

template <typename T> // T can be any float type (float, double, long double)
bool trackbar_float(T *theValue,
					T theMin, T theMax,
					int theNumberOfDecimals = 1,
					int theNumberOfLargeSteps = 1,
					T theSmallStep = -1.,
					bool flagForceValuesAsMultiplesOfSmallStep = false);

````

**Comment by Dovyski** [comment]
> The visual of the example is trackbar.png

That looks really cool! Definitely a trackbar component is useful for cvui. You also gave it a significant amount of customization, which also good.

> I made another modification about your concern about the immediate api.
> Now, you have 2 specialized functions, dependog on whether you want to edit integral for floating point values.

That's much better and aligned with the rest of the lib, thank you! The only "non-conformant" thing I see is the `_int` and `_float`  suffixes. I haven't used such differentiation for other components which also deal with `int` and `float` versions (e.g. counter). I just overloaded the function with different parameters.

Do you think you could do the same with trackbar?

**Comment by pthom** [comment]
There you go !

https://github.com/Dovyski/cvui/pull/6/commits/ba387e08a56daa492d4f8110f0233d95eb588d56

Sample usage here : 
https://github.com/pthom/cvui/blob/shortcuts_trackbar/example/src/trackbar/main.cpp

And the look & feel :
[trackbar.png](https://postimg.org/image/p111illtj/)

**Pull request merged**
