### PR TITLE
Removed line 2108 in cvui.h

### PR DESCRIPTION
**Pull request by Andyalevy**
Hi. This PR solves the bug stated in #71.

### CODE REVIEW

**Comment by Dovyski** [comment]
Hi and thank you for your contributions! Pull requests should be made against the `dev` branch of cvui instead of `master`. Do you mind changing your pull request to target the `dev` branch, please?

**Comment by Andyalevy** [comment]
I changed the base to dev. Sorry for the misunderstanding.

**Comment by Dovyski** [comment]
Thank you! No need to be sorry, it's my own fault not to document those things ;)

**Comment by Dovyski** [comment]
Thank you! 🎉 I'll merge your PR along with the other PRs as soon as I have some free time to work on cvui.

**Comment by Andyalevy** [comment]
Thanks! And thank you for the work you've done, cvui is extremely useful :)

**Comment by Dovyski** [comment]
The pleasure is all mine to see cvui being used. And to receive time and energy from other developers to help improve it. Thank you! :)

**Comment by freetomik** [comment]
Hello, remainder, that this should be merged. Almost year after this report, I hit the assertion error of #81 in debug mode. So I fixed it locally, and then found this old report. Please merge...

**Comment by Dovyski** [comment]
Ok, merged. I am truly sorry for the absence regarding the maintenance of this project in the last year. I am doing my best to allocate time for it.

**Comment by freetomik** [comment]
Thank you for the merge. I can understand the lack of time. Thanks for this useful tool.

**Pull request merged**
