### PR TITLE
cpp code highlighting issue (#27)

### PR DESCRIPTION
**Pull request by ksakash**
``{% highlight c++ %} .... {% endhighlight %}`` not working, for all the .md files in the docs, so replaced it with ```` ```cpp....``` ````

### CODE REVIEW

**Comment by Dovyski** [comment]
Thank you for your contribution and help!

Could you please tell me a bit more about how they are not working? I've just checked [cvui's online docs](https://dovyski.github.io/cvui/), e.g. [button page](https://dovyski.github.io/cvui/components/button/), and `{% highlight c++ %} .... {% endhighlight %}` is working.

Did you encounter the problem while trying to render the docs locally using jekyll?

**Comment by ksakash** [comment]
Not locally, but when i was reading the docs on github repo.

**Comment by Dovyski** [comment]
Oh, I see. Your solution is much better (I didn't like the `{% highlight%}` thing). I will just check the changes locally before accepting the pull request.

**Comment by Dovyski** [comment]
All changes have been merged. Thank you very much for your time and contribution!

**Pull request merged**
