### PR TITLE
Headless

### PR DESCRIPTION
**Pull request by jmuncaster**
I added a feature to enable a "headless" mode to my fork and wanted to contribute back to this project if this is feature you think is appropriate.

A headless mode enables all of the cvui functions, but does not actually create a GUI. This is useful for applications that (for example) use cvui for off-screen drawing and save their results to disk.

I attempted to follow repository style, but the tabs were an issue for me (sorry).
Also the attached example does not have a Visual Studio project or a python example.

### CODE REVIEW

**Comment by Dovyski** [comment]
That's great, thanks for the contribution! It will also be useful to implement some automated CI testing of cvui (which only checks for compilation errors at the moment).

I will not merge this PR right away because of the ongoing beta, but it will be merged as soon as `2.7.0` is officially out.

**Comment by Dovyski** [comment]
Ok, merged. I am truly sorry for the absence regarding the maintenance of this project. I am doing my best to allocate time for it.

**Comment by jmuncaster** [comment]
Thanks!!

**Comment by Dovyski** [comment]
I am the one to thank you!

**Pull request merged**
